//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WroseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project_Details()
        {
            this.Scenario_Details = new HashSet<Scenario_Details>();
            this.Waste_Mat_Details = new HashSet<Waste_Mat_Details>();
        }
    
        public int ID { get; set; }
        public string Project_Name { get; set; }
        public int Study_Year { get; set; }
        public string Client_Name { get; set; }
        public string Author_Name { get; set; }
        public string Author_company { get; set; }
        public string Local_Auth_Study { get; set; }
        public string Project_Desc { get; set; }
        public string Stusy_Purpose { get; set; }
        public string Key_Assumption { get; set; }
        public string Study_Limitation { get; set; }
        public int User_Reg_ID { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scenario_Details> Scenario_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waste_Mat_Details> Waste_Mat_Details { get; set; }
        public virtual User_Registration User_Registration { get; set; }
    }
}
