//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WroseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scenario_Details()
        {
            this.Scenario_Connection_Details = new HashSet<Scenario_Connection_Details>();
            this.Scenario_Node_details = new HashSet<Scenario_Node_details>();
        }
    
        public int ID { get; set; }
        public int Project_ID { get; set; }
        public string Scenario_Name { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<byte> IsDefault { get; set; }
        public int Category_ID { get; set; }
        public int Number_Of_Elements { get; set; }
    
        public virtual Category_Master Category_Master { get; set; }
        public virtual Project_Details Project_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scenario_Connection_Details> Scenario_Connection_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scenario_Node_details> Scenario_Node_details { get; set; }
    }
}
