//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WroseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario_Connection_Details
    {
        public int Scenario_ID { get; set; }
        public string Connection_ID { get; set; }
        public string Page_Source_ID { get; set; }
        public string Page_Target_ID { get; set; }
        public int ID { get; set; }
    
        public virtual Scenario_Details Scenario_Details { get; set; }
    }
}
