//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WroseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario_Node_details
    {
        public int ID { get; set; }
        public int Scenario_ID { get; set; }
        public string Block_ID { get; set; }
        public int Waste_Tech_ID { get; set; }
        public int Position_X { get; set; }
        public int Position_Y { get; set; }
    
        public virtual Scenario_Details Scenario_Details { get; set; }
        public virtual Waste_tech_Master Waste_tech_Master { get; set; }
    }
}
