//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WroseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role_Permission
    {
        public int ID { get; set; }
        public int User_Role_ID { get; set; }
        public int User_Permission_ID { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual User_Permission_Master User_Permission_Master { get; set; }
        public virtual User_Role_Master User_Role_Master { get; set; }
    }
}
