//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WroseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waste_Mat_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Waste_Mat_Master()
        {
            this.Waste_Mat_Details = new HashSet<Waste_Mat_Details>();
        }
    
        public int ID { get; set; }
        public string Waste_Mat_Name { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waste_Mat_Details> Waste_Mat_Details { get; set; }
    }
}
