//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WroseModel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WROSEDBEntities : DbContext
    {
        public WROSEDBEntities()
            : base("name=WROSEDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_Master> Category_Master { get; set; }
        public virtual DbSet<Municipality_Master> Municipality_Master { get; set; }
        public virtual DbSet<Project_Details> Project_Details { get; set; }
        public virtual DbSet<Provience_Master> Provience_Master { get; set; }
        public virtual DbSet<Scenario_Connection_Details> Scenario_Connection_Details { get; set; }
        public virtual DbSet<Scenario_Details> Scenario_Details { get; set; }
        public virtual DbSet<Scenario_Master> Scenario_Master { get; set; }
        public virtual DbSet<Scenario_Node_details> Scenario_Node_details { get; set; }
        public virtual DbSet<User_Permission_Master> User_Permission_Master { get; set; }
        public virtual DbSet<User_Registration> User_Registration { get; set; }
        public virtual DbSet<User_Role_Master> User_Role_Master { get; set; }
        public virtual DbSet<User_Role_Permission> User_Role_Permission { get; set; }
        public virtual DbSet<Waste_Mat_Details> Waste_Mat_Details { get; set; }
        public virtual DbSet<Waste_Mat_Master> Waste_Mat_Master { get; set; }
        public virtual DbSet<Waste_tech_Master> Waste_tech_Master { get; set; }
    }
}
